/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_gaurabda_GCalManager */

#ifndef _Included_org_gaurabda_GCalManager
#define _Included_org_gaurabda_GCalManager
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_gaurabda_GCalManager
 * Method:    nativeGCal4Query
 */
JNIEXPORT jstring JNICALL Java_org_gaurabda_GCalManager_nativeGCal4Query(JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
